### ISSUE TITLE
How to run repolist.py

### ISSUE THREAD

**Issue by arjunvijayvargiya** [larsks/github-tools#1]
I am getting following error
Traceback (most recent call last):
  File "/usr/lib/python3.4/py_compile.py", line 124, in compile
    _optimize=optimize)
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "./prog.py", line 76
    print '\n'.join(x['url'] for x in repos)
             ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/py_compile.py", line 128, in compile
    raise py_exc
py_compile.PyCompileError:   File "./prog.py", line 76
    print '\n'.join(x['url'] for x in repos)
             ^
SyntaxError: invalid syntax

**Comment by larsks** [comment]
This code was written for Python 2 and you are attempting to run it with Python 3.  One of the key differences between these two versions of Python is the `print` statement.  Feel free to submit a patch to make this code work under Python 3, or just use a Python 2 interpreter.
